### PR TITLE
Fix invalid number notations

### PR DESCRIPTION
**Pull request by s0meone**
Indexes where wrongly numbered with the octal notation.

### CODE REVIEW

**Comment by aborovsky** [comment]
Hi, Daniel!
Thx for contribution.
Was invalid index number notation causing some error?

**Comment by s0meone** [comment]
Yea it was, I was trying to pack all the source files into one with Browserify which failed because the numbers were invalid.

The command I used: `browserify index.js -o knx.js`.

Thanks for merging!

**Comment by aborovsky** [comment]
Do you need current lib to be republished under npm repo?

**Comment by s0meone** [comment]
No not necessarily, I'm working on some other fixes as well. I'll send the pull request(s) when I'm ready!

**Pull request merged**
